namespace MOD4.Web.DomainService.Entity
{
    public class INXRpt418Entity
    {
        public decimal ACTUAL_QTY { get; set; }
        public decimal CHANGE_QTY { get; set; }
        public string COMMENT1 { get; set; }
        public decimal DAYS { get; set; }
        public string DUE_DT { get; set; }
        public string ENGINEER { get; set; }
        public decimal FAC_ID { get; set; }
        public decimal? HOLD_WIP_1050 { get; set; }
        public decimal? HOLD_WIP_1100 { get; set; }
        public decimal? HOLD_WIP_1200 { get; set; }
        public decimal? HOLD_WIP_1300 { get; set; }
        public decimal? HOLD_WIP_1305 { get; set; }
        public decimal? HOLD_WIP_1320 { get; set; }
        public decimal? HOLD_WIP_1322 { get; set; }
        public decimal? HOLD_WIP_1323 { get; set; }
        public decimal? HOLD_WIP_1329 { get; set; }
        public decimal? HOLD_WIP_1330 { get; set; }
        public decimal? HOLD_WIP_1340 { get; set; }
        public decimal? HOLD_WIP_1355 { get; set; }
        public decimal? HOLD_WIP_1356 { get; set; }
        public decimal? HOLD_WIP_1361 { get; set; }
        public decimal? HOLD_WIP_1363 { get; set; }
        public decimal? HOLD_WIP_1364 { get; set; }
        public decimal? HOLD_WIP_1366 { get; set; }
        public decimal? HOLD_WIP_1370 { get; set; }
        public decimal? HOLD_WIP_1389 { get; set; }
        public decimal? HOLD_WIP_1398 { get; set; }
        public decimal? HOLD_WIP_1400 { get; set; }
        public decimal? HOLD_WIP_1405 { get; set; }
        public decimal? HOLD_WIP_1407 { get; set; }
        public decimal? HOLD_WIP_1415 { get; set; }
        public decimal? HOLD_WIP_1416 { get; set; }
        public decimal? HOLD_WIP_1417 { get; set; }
        public decimal? HOLD_WIP_1418 { get; set; }
        public decimal? HOLD_WIP_1419 { get; set; }
        public decimal? HOLD_WIP_1420 { get; set; }
        public decimal? HOLD_WIP_1426 { get; set; }
        public decimal? HOLD_WIP_1427 { get; set; }
        public decimal? HOLD_WIP_1430 { get; set; }
        public decimal? HOLD_WIP_1442 { get; set; }
        public decimal? HOLD_WIP_1443 { get; set; }
        public decimal? HOLD_WIP_1444 { get; set; }
        public decimal? HOLD_WIP_1450 { get; set; }
        public decimal? HOLD_WIP_1453 { get; set; }
        public decimal? HOLD_WIP_1460 { get; set; }
        public decimal? HOLD_WIP_1500 { get; set; }
        public decimal? HOLD_WIP_1503 { get; set; }
        public decimal? HOLD_WIP_1507 { get; set; }
        public decimal? HOLD_WIP_1508 { get; set; }
        public decimal? HOLD_WIP_1510 { get; set; }
        public decimal? HOLD_WIP_1520 { get; set; }
        public decimal? HOLD_WIP_1550 { get; set; }
        public decimal? HOLD_WIP_1561 { get; set; }
        public decimal? HOLD_WIP_1562 { get; set; }
        public decimal? HOLD_WIP_1580 { get; set; }
        public decimal? HOLD_WIP_1600 { get; set; }
        public decimal? HOLD_WIP_1630 { get; set; }
        public decimal? HOLD_WIP_1700 { get; set; }
        public decimal? HOLD_WIP_1720 { get; set; }
        public decimal? HOLD_WIP_1750 { get; set; }
        public decimal? HOLD_WIP_1752 { get; set; }
        public decimal? HOLD_WIP_1753 { get; set; }
        public decimal? HOLD_WIP_1760 { get; set; }
        public decimal? HOLD_WIP_1770 { get; set; }
        public decimal? HOLD_WIP_1800 { get; set; }
        public decimal? HOLD_WIP_1830 { get; set; }
        public decimal? HOLD_WIP_1845 { get; set; }
        public decimal? HOLD_WIP_1910 { get; set; }
        public decimal? HOLD_WIP_2100 { get; set; }
        public decimal? HOLD_WIP_2109 { get; set; }
        public decimal? HOLD_WIP_2400 { get; set; }
        public decimal? HOLD_WIP_2600 { get; set; }
        public decimal? HOLD_WIP_2900 { get; set; }
        public string LCM_OWNER { get; set; }
        public decimal MVIN_RATE { get; set; }
        public decimal MVOU_RATE { get; set; }
        public decimal NEWQTY { get; set; }
        public decimal? NON_HOLD_WIP_0 { get; set; }
        public decimal? NON_HOLD_WIP_1000 { get; set; }
        public decimal? NON_HOLD_WIP_1050 { get; set; }
        public decimal? NON_HOLD_WIP_1100 { get; set; }
        public decimal? NON_HOLD_WIP_1200 { get; set; }
        public decimal? NON_HOLD_WIP_1300 { get; set; }
        public decimal? NON_HOLD_WIP_1305 { get; set; }
        public decimal? NON_HOLD_WIP_1320 { get; set; }
        public decimal? NON_HOLD_WIP_1321 { get; set; }
        public decimal? NON_HOLD_WIP_1322 { get; set; }
        public decimal? NON_HOLD_WIP_1323 { get; set; }
        public decimal? NON_HOLD_WIP_1329 { get; set; }
        public decimal? NON_HOLD_WIP_1330 { get; set; }
        public decimal? NON_HOLD_WIP_1331 { get; set; }
        public decimal? NON_HOLD_WIP_1340 { get; set; }
        public decimal? NON_HOLD_WIP_1354 { get; set; }
        public decimal? NON_HOLD_WIP_1355 { get; set; }
        public decimal? NON_HOLD_WIP_1356 { get; set; }
        public decimal? NON_HOLD_WIP_1361 { get; set; }
        public decimal? NON_HOLD_WIP_1363 { get; set; }
        public decimal? NON_HOLD_WIP_1364 { get; set; }
        public decimal? NON_HOLD_WIP_1365 { get; set; }
        public decimal? NON_HOLD_WIP_1366 { get; set; }
        public decimal? NON_HOLD_WIP_1370 { get; set; }
        public decimal? NON_HOLD_WIP_1374 { get; set; }
        public decimal? NON_HOLD_WIP_1380 { get; set; }
        public decimal? NON_HOLD_WIP_1389 { get; set; }
        public decimal? NON_HOLD_WIP_1395 { get; set; }
        public decimal? NON_HOLD_WIP_1397 { get; set; }
        public decimal? NON_HOLD_WIP_1398 { get; set; }
        public decimal? NON_HOLD_WIP_1399 { get; set; }
        public decimal? NON_HOLD_WIP_1400 { get; set; }
        public decimal? NON_HOLD_WIP_1405 { get; set; }
        public decimal? NON_HOLD_WIP_1406 { get; set; }
        public decimal? NON_HOLD_WIP_1407 { get; set; }
        public decimal? NON_HOLD_WIP_1415 { get; set; }
        public decimal? NON_HOLD_WIP_1416 { get; set; }
        public decimal? NON_HOLD_WIP_1417 { get; set; }
        public decimal? NON_HOLD_WIP_1418 { get; set; }
        public decimal? NON_HOLD_WIP_1419 { get; set; }
        public decimal? NON_HOLD_WIP_1420 { get; set; }
        public decimal? NON_HOLD_WIP_1421 { get; set; }
        public decimal? NON_HOLD_WIP_1425 { get; set; }
        public decimal? NON_HOLD_WIP_1426 { get; set; }
        public decimal? NON_HOLD_WIP_1427 { get; set; }
        public decimal? NON_HOLD_WIP_1430 { get; set; }
        public decimal? NON_HOLD_WIP_1440 { get; set; }
        public decimal? NON_HOLD_WIP_1441 { get; set; }
        public decimal? NON_HOLD_WIP_1442 { get; set; }
        public decimal? NON_HOLD_WIP_1443 { get; set; }
        public decimal? NON_HOLD_WIP_1444 { get; set; }
        public decimal? NON_HOLD_WIP_1445 { get; set; }
        public decimal? NON_HOLD_WIP_1450 { get; set; }
        public decimal? NON_HOLD_WIP_1460 { get; set; }
        public decimal? NON_HOLD_WIP_1481 { get; set; }
        public decimal? NON_HOLD_WIP_1500 { get; set; }
        public decimal? NON_HOLD_WIP_1503 { get; set; }
        public decimal? NON_HOLD_WIP_1507 { get; set; }
        public decimal? NON_HOLD_WIP_1508 { get; set; }
        public decimal? NON_HOLD_WIP_1510 { get; set; }
        public decimal? NON_HOLD_WIP_1520 { get; set; }
        public decimal? NON_HOLD_WIP_1550 { get; set; }
        public decimal? NON_HOLD_WIP_1560 { get; set; }
        public decimal? NON_HOLD_WIP_1561 { get; set; }
        public decimal? NON_HOLD_WIP_1580 { get; set; }
        public decimal? NON_HOLD_WIP_1581 { get; set; }
        public decimal? NON_HOLD_WIP_1590 { get; set; }
        public decimal? NON_HOLD_WIP_1600 { get; set; }
        public decimal? NON_HOLD_WIP_1630 { get; set; }
        public decimal? NON_HOLD_WIP_1660 { get; set; }
        public decimal? NON_HOLD_WIP_1700 { get; set; }
        public decimal? NON_HOLD_WIP_1720 { get; set; }
        public decimal? NON_HOLD_WIP_1740 { get; set; }
        public decimal? NON_HOLD_WIP_1750 { get; set; }
        public decimal? NON_HOLD_WIP_1752 { get; set; }
        public decimal? NON_HOLD_WIP_1753 { get; set; }
        public decimal? NON_HOLD_WIP_1760 { get; set; }
        public decimal? NON_HOLD_WIP_1770 { get; set; }
        public decimal? NON_HOLD_WIP_1800 { get; set; }
        public decimal? NON_HOLD_WIP_1810 { get; set; }
        public decimal? NON_HOLD_WIP_1830 { get; set; }
        public decimal? NON_HOLD_WIP_1845 { get; set; }
        public decimal? NON_HOLD_WIP_1850 { get; set; }
        public decimal? NON_HOLD_WIP_1855 { get; set; }
        public decimal? NON_HOLD_WIP_1910 { get; set; }
        public decimal? NON_HOLD_WIP_1940 { get; set; }
        public decimal? NON_HOLD_WIP_2100 { get; set; }
        public decimal? NON_HOLD_WIP_2109 { get; set; }
        public decimal? NON_HOLD_WIP_2110 { get; set; }
        public decimal? NON_HOLD_WIP_2130 { get; set; }
        public decimal? NON_HOLD_WIP_2300 { get; set; }
        public decimal? NON_HOLD_WIP_2310 { get; set; }
        public decimal? NON_HOLD_WIP_2320 { get; set; }
        public decimal? NON_HOLD_WIP_2330 { get; set; }
        public decimal? NON_HOLD_WIP_2340 { get; set; }
        public decimal? NON_HOLD_WIP_2400 { get; set; }
        public decimal? NON_HOLD_WIP_2405 { get; set; }
        public decimal? NON_HOLD_WIP_2410 { get; set; }
        public decimal? NON_HOLD_WIP_2440 { get; set; }
        public decimal? NON_HOLD_WIP_2600 { get; set; }
        public decimal? NON_HOLD_WIP_2610 { get; set; }
        public decimal? NON_HOLD_WIP_2620 { get; set; }
        public decimal? NON_HOLD_WIP_2650 { get; set; }
        public decimal? NON_HOLD_WIP_2660 { get; set; }
        public decimal? NON_HOLD_WIP_2900 { get; set; }
        public decimal? NON_HOLD_WIP_6001 { get; set; }
        public decimal? NON_HOLD_WIP_9011 { get; set; }
        public decimal? NON_HOLD_WIP_9910 { get; set; }
        public string PLAN_ST_DT { get; set; }
        public string PROD_NBR { get; set; }
        public string PROD_SIZE { get; set; }
        public string PROD_TYPE { get; set; }
        public string RELEASE_DT { get; set; }
        public decimal REMAIN { get; set; }
        public decimal SCRAP_QTY { get; set; }
        public decimal SHIP_QTY { get; set; }
        public string STATUS { get; set; }
        public decimal TARGET_QTY { get; set; }
        public string VER { get; set; }
        public decimal? WIP_ALL { get; set; }
        public decimal? WIP_ASSY { get; set; }
        public decimal? WIP_BOND { get; set; }
        public decimal? WIP_CD1 { get; set; }
        public decimal? WIP_CD2 { get; set; }
        public decimal? WIP_HOLD { get; set; }
        public decimal? WIP_LAM { get; set; }
        public decimal? WIP_NON_HOLD { get; set; }
        public decimal? WIP_RWK { get; set; }
        public string WO_NBR { get; set; }
        public string WO_STATUS { get; set; }
        public string WO_TYPE { get; set; }
    }
}
